version: "3.8"

services:
  fastapi:
    image: fastapi_startup:latest
    build: .
    container_name: fastapi_startup
    ports:
      - "8088:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # depends_on:
    #   - mongodb