version: "3.2"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./init-mongo-script.js:/docker-entrypoint-initdb.d/init-mongo-script.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 79e0c45cbf8d31f4
  