version: "3.8"

services:
  fastapi:
    image: fastapi_startup:latest
    build: .
    container_name: fastapi_startup
    ports:
      - "8088:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - default_network
    depends_on:
      - mongodb
    # restart: always
    

  mongodb:
    image: mongo:latest
    container_name: mongodb_startup
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./init-mongo-script.js:/docker-entrypoint-initdb.d/init-mongo-script.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 79e0c45cbf8d31f4
    networks:
      - default_network
    # restart: always

  postgres:
    image: postgres:latest
    container_name: postgresdb_startup
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: f231d66faef47a6e
    networks:
      - default_network
    # restart: always


networks:
  default_network:
    driver: bridge