version: "3.8"

services:
  mongodb:
    image: postgres:latest
    container_name: postgres_startup
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: f231d66faef47a6e